apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bami-argo-app-01
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/sseoseungbeom/bami-app-argocd.git'
    targetRevision: HEAD
    path: app-argo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
